namespace SocialSense.UrlBuilders.Parameters
{
    using System.Collections.Generic;

    using SocialSense.Shared;

    public class GooglePlusLocation : ILocation
    {
        private readonly IDictionary<Language, string> languages = new Dictionary<Language, string>
            {
                { Language.Abkhazian, string.Empty },
                { Language.Afar, string.Empty },
                { Language.Afrikaans, "af" },
                { Language.Akan, string.Empty },
                { Language.Albanian, string.Empty },
                { Language.Amharic, "am" },
                { Language.Arabic, "ar" },
                { Language.Aragonese, string.Empty },
                { Language.Armenian, string.Empty },
                { Language.Assamese, string.Empty },
                { Language.Avaric, string.Empty },
                { Language.Avestan, string.Empty },
                { Language.Aymara, string.Empty },
                { Language.Azerbaijani, "eu" },
                { Language.Bambara, string.Empty },
                { Language.Bashkir, string.Empty },
                { Language.Basque, string.Empty },
                { Language.Belarusian, string.Empty },
                { Language.Bengali, "bn" },
                { Language.Bihari, string.Empty },
                { Language.Bislama, string.Empty },
                { Language.Bosnian, string.Empty },
                { Language.Breton, string.Empty },
                { Language.Bulgarian, "bg" },
                { Language.Burmese, string.Empty },
                { Language.Catalan, "ca" },
                { Language.Chamorro, string.Empty },
                { Language.Chechen, string.Empty },
                { Language.Chichewa, string.Empty },
                { Language.Chinese, "zh-TW" },
                { Language.ChurchSlavic, string.Empty },
                { Language.Chuvash, string.Empty },
                { Language.Cornish, string.Empty },
                { Language.Corsican, string.Empty },
                { Language.Cree, string.Empty },
                { Language.Croatian, "hr" },
                { Language.Czech, "cs" },
                { Language.Danish, "da" },
                { Language.Divehi, string.Empty },
                { Language.Dutch, "nl" },
                { Language.Dzongkha, string.Empty },
                { Language.English, "en-US" },
                { Language.Esperanto, string.Empty },
                { Language.Estonian, "et" },
                { Language.Ewe, string.Empty },
                { Language.Faroese, string.Empty },
                { Language.Fijian, string.Empty },
                { Language.Finnish, "fi" },
                { Language.French, "fr" },
                { Language.Fulah, string.Empty },
                { Language.Galician, "gl" },
                { Language.Ganda, string.Empty },
                { Language.Georgian, string.Empty },
                { Language.German, "de" },
                { Language.Greek, "el" },
                { Language.Guaraní, string.Empty },
                { Language.Gujarati, "gu" },
                { Language.Haitian, string.Empty },
                { Language.Hausa, string.Empty },
                { Language.Hebrew, "iw" },
                { Language.Herero, string.Empty },
                { Language.Hindi, "hi" },
                { Language.HiriMotu, string.Empty },
                { Language.Hungarian, "hu" },
                { Language.Icelandic, "is" },
                { Language.Ido, string.Empty },
                { Language.Igbo, string.Empty },
                { Language.Indonesian, "id" },
                { Language.Interlingua, string.Empty },
                { Language.Interlingue, string.Empty },
                { Language.Inuktitut, string.Empty },
                { Language.Inupiaq, string.Empty },
                { Language.Irish, string.Empty },
                { Language.Italian, "it" },
                { Language.Japanese, "ja" },
                { Language.Javanese, string.Empty },
                { Language.Kalaallisut, string.Empty },
                { Language.Kannada, "kn" },
                { Language.Kanuri, string.Empty },
                { Language.Kashmiri, string.Empty },
                { Language.Kazakh, string.Empty },
                { Language.Khmer, string.Empty },
                { Language.Kikuyu, string.Empty },
                { Language.Kinyarwanda, string.Empty },
                { Language.Kirghiz, string.Empty },
                { Language.Kirundi, string.Empty },
                { Language.Komi, string.Empty },
                { Language.Kongo, string.Empty },
                { Language.Korean, "ko" },
                { Language.Kurdish, string.Empty },
                { Language.Kwanyama, string.Empty },
                { Language.Lao, string.Empty },
                { Language.Latin, string.Empty },
                { Language.Latvian, "lv" },
                { Language.Limburgish, string.Empty },
                { Language.Lingala, string.Empty },
                { Language.Lithuanian, "lt" },
                { Language.LubaKatanga, string.Empty },
                { Language.Luxembourgish, string.Empty },
                { Language.Macedonian, string.Empty },
                { Language.Malagasy, string.Empty },
                { Language.Malay, "ms" },
                { Language.Malayalam, "ml" },
                { Language.Maltese, string.Empty },
                { Language.Manx, string.Empty },
                { Language.Maori, string.Empty },
                { Language.Marathi, "mr" },
                { Language.Marshallese, string.Empty },
                { Language.Mongolian, string.Empty },
                { Language.Nauru, string.Empty },
                { Language.Navajo, string.Empty },
                { Language.Ndonga, string.Empty },
                { Language.Nepali, string.Empty },
                { Language.NorthernSami, string.Empty },
                { Language.NorthNdebele, string.Empty },
                { Language.Norwegian, "no" },
                { Language.NorwegianBokmal, string.Empty },
                { Language.NorwegianNynors, string.Empty },
                { Language.Occitan, string.Empty },
                { Language.Ojibwa, string.Empty },
                { Language.Oriya, string.Empty },
                { Language.Oromo, string.Empty },
                { Language.Ossetian, string.Empty },
                { Language.Pali, string.Empty },
                { Language.Panjabi, string.Empty },
                { Language.Pashto, string.Empty },
                { Language.Persian, "fa" },
                { Language.Polish, "pl" },
                { Language.Portuguese, "pt-PT" },
                { Language.Quechua, string.Empty },
                { Language.RaetoRomance, string.Empty },
                { Language.Romanian, "ro" },
                { Language.Russian, "ru" },
                { Language.Samoan, string.Empty },
                { Language.Sango, string.Empty },
                { Language.Sanskrit, string.Empty },
                { Language.Sardinian, string.Empty },
                { Language.ScottishGaelic, string.Empty },
                { Language.Serbian, "sr" },
                { Language.SerboCroatian, string.Empty },
                { Language.Shona, string.Empty },
                { Language.SichuanYi, string.Empty },
                { Language.Sindhi, string.Empty },
                { Language.Sinhala, string.Empty },
                { Language.Slovak, "sk" },
                { Language.Slovenian, "sl" },
                { Language.Somali, string.Empty },
                { Language.SouthernSotho, string.Empty },
                { Language.SouthNdebele, string.Empty },
                { Language.Spanish, "es" },
                { Language.Sundanese, string.Empty },
                { Language.Swahili, "sw" },
                { Language.Swati, string.Empty },
                { Language.Swedish, "sv" },
                { Language.Tagalog, string.Empty },
                { Language.Tahitian, string.Empty },
                { Language.Tajik, string.Empty },
                { Language.Tamil, "ta" },
                { Language.Tatar, string.Empty },
                { Language.Telugu, "te" },
                { Language.Thai, "th" },
                { Language.Tibetan, string.Empty },
                { Language.Tigrinya, string.Empty },
                { Language.Tonga, string.Empty },
                { Language.Tsonga, string.Empty },
                { Language.Tswana, string.Empty },
                { Language.Turkish, "tr" },
                { Language.Turkmen, string.Empty },
                { Language.Twi, string.Empty },
                { Language.Uighur, string.Empty },
                { Language.Ukrainian, "uk" },
                { Language.Undefined, string.Empty },
                { Language.Urdu, "ur" },
                { Language.Uzbek, string.Empty },
                { Language.Venda, string.Empty },
                { Language.Vietnamese, "vi" },
                { Language.Volapük, string.Empty },
                { Language.Walloon, string.Empty },
                { Language.Welsh, string.Empty },
                { Language.WesternFrisian, string.Empty },
                { Language.Wolof, string.Empty },
                { Language.Xhosa, string.Empty },
                { Language.Yiddish, string.Empty },
                { Language.Yoruba, string.Empty },
                { Language.Zhuang, string.Empty },
                { Language.Zulu, "zu" },
                { Language.BrazilianPortuguese, "pt-BR" }
            };
        
        public string GetCountry(Country country)
        {
            return string.Empty;
        }

        public string GetLanguage(Language language)
        {
            return this.languages[language];
        }
    }
}
